id: P54AE58B4
initial_creation_type: input
source_metadata:
  title: Guru Padmasambhava
  language: de
  description: 'Prayers to the Precious Guru Padmasambhava or Padmākara (padma ''byung
    gnas), the "Lotus-Born", who is credited with establishing Buddhism in Tibet:'
  volume:
    69faab867fc54115bb0f0dc75b32731e:
      title: A Synopsis of Guru Padmasambhava’s Life
      parent: Alak Zenkar Pema Ngödrup Rolwe Dorje
    ff6c0627dbf34c959ad3a35650d1c5d2:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Dudjom Rinpoche
    1636f0f6162f4bba898480038d5d6a80:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Chokgyur Dechen Lingpa
    39ed5bf3187d4f8a82631e948465e641:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    2fdafb5fafe14491a127a30eeb736220:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    b300cb7a1d0d4036ab540a9c7dff26b7:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Chokgyur Dechen Lingpa
    b4f5b11631ef41f7b930f982927c697b:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    d236fbe0607a4f8ba39d41f856b41050:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    6cb220c1e17244e68e7d4d6c460ec7fb:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    67c5984d4f2a4d0fb16fec9e7b84937d:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Chokgyur Dechen Lingpa
    d88de2704fc745b8996d68b342d5e624:
      title: 'A Garland of Vajra Words: A Prayer to the Guru'
      parent: Dilgo Khyentse Rinpoche
    6cdcb3c099cc46ee8d362d3aeca100e6:
      title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in
        Eight Chapters'
      parent: Dilgo Khyentse Rinpoche
    6bd98967377a482895ecad8e2d6c68e3:
      title: The Prayer to Swiftly Fulfil All Wishes
      parent: Dilgo Khyentse Rinpoche
    97682ebb7ac243e8a7b7d008094a681f:
      title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
      parent: Dilgo Khyentse Rinpoche
    bb156c1081944c918008826c3d9eb326:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    4303c34ddd1749f495db5ed9a52225b5:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    61ca74a213c34de398c1a202d940e151:
      title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
      parent: Dodrupchen Jigme Tenpe Nyima
    a623db17f31b4d8aa1c218a22e96288a:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Dodrupchen Jigme Tenpe Nyima
    6d1a83494dcc498dae8da358d0bef694:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    3c6b1ff825eb4499b6de90ea645cd393:
      title: A Prayer to Padmasambhava
      parent: Dudjom Lingpa
    85912d5cd71c4abeb57c6f32fd68142a:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Dudjom Rinpoche
    8894871abd5e4d669ea5de3b0afde059:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Dudjom Rinpoche
    6ebba7e476ac4a1f8359abc6214dae1e:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Dudjom Rinpoche
    1cf0fa565bf3478ab3d26b119961b204:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Dudjom Rinpoche
    5cb68c74904c48bd8abcf5811f845742:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Dudjom Rinpoche
    d4b783b0b34344dba58d1ab599a2f5d8:
      title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils
        All Wishes
      parent: Dzongter Kunzang Nyima
    17ffb1e458fd497a995de2e95635664c:
      title: 'Cloud Banks of Blessings: A Prayer to Guru Padmasambhava'
      parent: Fifth Dalai Lama
    d6103ed48db2484f951a652207b51534:
      title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate
        Teacher Padmasambhava
      parent: Fourteenth Dalai Lama
    d7fd952531f44ccfb85846d7b38c37b0:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    b6b06b57865047eb93a044de4cb24321:
      title: Prayer to Orgyen Rinpoche Invoking His Wisdom Mind
      parent: Gönpo Tseten Rinpoche
    dd4ec61187f244c2b84e1b4091f4aea9:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Jamgön Kongtrul
    17b78e8b0b1b43ad8931c169be2f86a7:
      title: A Heart Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    f83fb4f5938e43338e9e09a154a01b16:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Jamyang Khyentse Chökyi Lodrö
    167f4e8283d74ae39af4353765d8f604:
      title: A Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    4b884ebfa56945e39bacb8373a4bc661:
      title: A Yearning Plea to the Precious Guru
      parent: Jamyang Khyentse Chökyi Lodrö
    08eb6252bfcd4390aedae8688f1359f7:
      title: 'Cloud Banks of Blessings: A Prayer to Orgyen Rinpoche'
      parent: Jamyang Khyentse Chökyi Lodrö
    46f7baf06f2e4fb5b684e0f7d2a112af:
      title: Prayer of the Wisdom Mind
      parent: Jamyang Khyentse Chökyi Lodrö
    e07a4b08fdab4483936b679b280d6d68:
      title: Spontaneous Fulfilment of Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    437be4dab2a543f4a773441d37c1a4a1:
      title: The Falling Elixir of Blessing
      parent: Jamyang Khyentse Chökyi Lodrö
    031584dcb35d4d6b87df93019b783286:
      title: 'The Fulfilment of Wishes and Aspirations: A Prayer to Ācārya Padmasambhava'
      parent: Jamyang Khyentse Chökyi Lodrö
    3b6e71d81a884016be5036440928daf2:
      title: 'The Supreme Bestowal of Twofold Attainment: A Prayer to Orgyen Rinpoche,
        Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Chökyi Lodrö
    c73be2fb61054f37961b28717b9fb770:
      title: 'The Swift Fulfilment of Aspirations: A Prayer to Glorious Orgyen, King
        of Dharma'
      parent: Jamyang Khyentse Chökyi Lodrö
    486fdc10650e476bb87e288c8d98dfa2:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Jamyang Khyentse Chökyi Lodrö
    ff2bcec3448447d883813dd7ee4030b7:
      title: To Fulfil All Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    745e914576384c0b9f3dd0feb4d84538:
      title: Turning Back the Misfortunes of the Age of Degeneration
      parent: Jamyang Khyentse Chökyi Lodrö
    dade834d05c84a6d81add1d3377ea2d9:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Jamyang Khyentse Wangpo
    41f55fd9539843159fcf36ff478d177e:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    1beb12b8d81d4b2b9e713d890f1cb04a:
      title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling
        to the Realm of Lotus Light'
      parent: Jamyang Khyentse Wangpo
    aefc946062ac4216a3dd3eabc540cc70:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    9143d7e3e836441581d268eaa365e735:
      title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche
        and the Twenty-Five Disciples, the King and Subjects'
      parent: Jamyang Khyentse Wangpo
    a0ea7bfadb004ddea7842fcd705c65d6:
      title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen
        Rinpoche, Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Wangpo
    6427de2635bd43c484466256bbfba071:
      title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
        the Precious Master of Oddiyana'
      parent: Jamyang Khyentse Wangpo
    e01197cd32b64f6ab8b26e4de76e9443:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Jigme Lingpa
    a8c27723b62945269df38415d79560f4:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Jigme Lingpa
    902801566f08439fa53c5820539d1469:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    2b577b2156064d91bf91be47e227dfc1:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Jigme Lingpa
    df4e4d83b9fa4cf4b518a72942809eea:
      title: Prayer to Pema Tötreng Tsal
      parent: Khenchen Ngawang Palzang
    7de2c62b7bfe42ec848733e63a9a2290:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Longchen Rabjam
    d172e29d8d35450a9b4683cca98246c5:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      parent: Menlungpa Mikyö Dorje
    388a2a3f7fa8420a99a352616db2c990:
      title: A Plaintive Prayer to Guru Rinpoche
      parent: Minling Chung Rinpoche
    f3632b5b76104d6890106fb0972e2754:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Mipham Rinpoche
    8d2b45b2567c4808ae9ec7eb805c5b69:
      title: Recollecting the Deeds of The Tenth Days
      parent: Mipham Rinpoche
    26325343ce854a738cf146389c106f33:
      title: The Prayer which is the Source of All True Realization
      parent: Mipham Rinpoche
    ee357feb8a6d430b8837f60fb0c10e5a:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Mipham Rinpoche
    71c56a193a814f7798fddb23c3a02283:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    8c2d9509c2f94e73b385e083da3a3b58:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    cc8a011e480c432fbb9bbc343098496b:
      title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
      parent: Pawo Lerab Tsal
    d81516fd894b430cba2032f1062e2947:
      title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles
        from the Path
      parent: Rangrik Dorje
    b39609e23e3a43f8b59a4859f8f367a8:
      title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils
        All Wishes
      parent: Rangrik Dorje
    46c997119450497584ce39219a1d9367:
      title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
      parent: Rangrik Dorje
    d1183f60e5c54525a250342ba805c000:
      title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of
        Uḍḍiyāna'
      parent: Rangrik Dorje
    9b300af3159c41d9aab07ca2f93c87fb:
      title: 'The Wish-Fulfilling Tree: A Prayer to the All-Embodying Lama Tsokye
        Dorje'
      parent: Rangrik Dorje
    ac857a21e95a4253b432f93f620b3cdf:
      title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom
        for the Swift Fulfilment of Wishes'
      parent: Rangrik Dorje
    8e6ea53c086e4a9bad08bb7773e4ba34:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Ratna Lingpa
    55aaf4aaee2f4148ba388ec37c24dfb3:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Ratna Lingpa
    995f788f4bff4c7a8f93c53292647240:
      title: A Prayer To Padmasambhava
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    dab0e1e4aaef441aa1cf270f252c258d:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    361c7aff269a4f198786032402b8367e:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Shechen Rabjam Rinpoche
    5d70aa57c4c546368493c3bc77474fcb:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Outlines
created_at: '2022-03-01T03:50:02.042208'
last_modified_at: '2022-03-01T03:50:02.042210'
